### PR TITLE
Nature of Documentation

### PR DESCRIPTION
**Pull request by cshubhamrao**
The present readme reads more like an advertisement and skips many important parts. Sure advertising is good, but README.md does not seem the best place to do it. Isn't wiki and gh-pages available for it already?

@mayukhnair Should we setup a website or wiki for all the promotional stuff?

### CODE REVIEW

**Comment by mayukhnair** [comment]
@cshubhamrao Yes, we can use a github.io page-or my personal domain (nah, this is a team effort)- for the website hosting. And a wiki is definitely a good idea.

**Comment by cshubhamrao** [comment]
@mayukhnair Please review the commits

**Comment by Dhiraj3108** [comment]
@cshubhamrao
I agree with you as well as @mayukhnair (bhaiya). Wiki is a nice option

**Comment by cshubhamrao** [comment]
@SecureHandshake/developers  please review the changes

**Comment by Dhiraj3108** [comment]
@cshubhamrao Yes there is need for a formal approach even if the present approach appeals to people more.

**Comment by mayukhnair** [comment]
I've thoroughly reviewed the pull request, and I do not agree with @cshubhamrao or @Dhiraj3108. For starters, Handshake shouldn't follow industry standards when it comes to description: we can allow mafia-like lawlessness there. Most people (read 90%) who will visit our GitHub repository will barely bother to go through the wiki pages; the README.md should act as a mini intro to the Handshake project. Following code style guides and a modus operandi for commits is encouraged, but let's not make it so businesslike. Let's make our README.md a rule-breaker readme. Anyone who means serious business can be pointed towards our wiki (our current README.md can be amended to include a wiki hyperlink.)

On that note, I hereby in the spirit of rule-bending and partial non-conformism propose that this pull request be rejected (sic).

**Comment by Dhiraj3108** [comment]
Being on a contradictory side I would like to go with @mayukhnair but there should be at least one(different) overview where the technicalities are concerned. (That should be somewhat official). Rest the remaining overview can be as such.

**Comment by cshubhamrao** [comment]
While Mafia-like lawlessness is tempting (who doesn't like mafias), let's not forget that `README` is **not** a thing end users _should_ or _would_ be reading. We're writing `README` for developers not for users.  Let's not forget the nature of GitHub, It's always _more likely_ that a given repo is viewed by a developer _not_ by an end user.

For users of our app the ideal place for all the stuff that matters to them is _GitHub Pages_. Everything concerning them including, but not limited to Overview (Non Technical), How to run/get it, FAQs etc. etc. **_should**_ be on the websites. We do't want fancy website telling developers how to compile our software.

For reference take a look at: [StackOverflow - How to write a good README](http://stackoverflow.com/a/2304870/2561129)

My proposal:
- **GitHub Pages:**The main end for interaction with the user (not the only). Should contain all the detailed overview about the Software with all the Mafia Lawlessness and N*\* Proofness with links to downloads. A FAQ may do wonders. May also contain pages to show how to use etc. etc.<br> 
  This thing is strictly **Non-Technical**.
- **Wiki:** The main end for interaction with seriously interested people.Should contain pages showing the technical inner working of our app and its constituent technologies (PGP, RSA, LZMA2). This will also contain pages showing the structure of our Software. Should be in sufficient detail such that anyone can become from zero to hero in knowing about the software. <br> This thing is **Technical**
- **README:** As the excellent SO answer points out README should be short, sweet and structured. Should answer such questions _briefly_:
  - What is this?
  - How should I get (compile) it?
  - How should I contribute
  - Where can I get more info

Aaand remember, READMEs exist for a reason :smile:

**Comment by cshubhamrao** [comment]
@SecureHandshake/developers Added a dummy github page. Make it awesome by changing and adding fies to the `gh-pages` branch

**Comment by mayukhnair** [comment]
@cshubhamrao, your argument is really impressive. And guess what, I'm agreeing with you. Let's make the README.md technical- but don't merge this pull request yet. Let us create a good-looking project website (first impression is the last impression) we're all satisfied with, and then take this README.md down. Until then, this repository page acts as the interim official page for the Handshake page and once done with the website, we'll merge your pull request.

**Comment by cshubhamrao** [comment]
@SecureHandshake/developers At this point I consider the `README` to have matured, giving just the right amount of information to get any dev started.
Please read the finished [`README`](https://github.com/SecureHandshake/HandshakeApp/blob/feature/documentation-fix/README.md) and comment

**Comment by cshubhamrao** [comment]
@mayukhnair no hurry to merge, let gh-pages be setup satisfactorily

**Comment by Dhiraj3108** [comment]
Agree with the all new README. Satisfied even if i haven't understood all of it. :+1:

**Comment by aditya-nair** [comment]
Eh sudo and Mayukh Anna
Leave the webpage design to me
If you are expecting to make one

**Comment by aditya-nair** [comment]
Should I help with the readme

**Comment by aditya-nair** [comment]
???

**Comment by mayukhnair** [comment]
What? This web page isn't good? :'(

Yeah, you can help Shubham with the readme.

**Comment by cshubhamrao** [comment]
@adinarad @aditya-nair Any comments, After 10PM this pull request will be locked

**Comment by cshubhamrao** [comment]
Should I merge this now?

**Comment by mayukhnair** [comment]
Go ahead.

**Comment by adinarad** [comment]
read me is like[?]

**Comment by mayukhnair** [comment]
Like what?

On the other hand, @cshubhamrao, please close this issue now that merging
is complete.

**Pull request merged**
